insert into businesses (company, service_type, owner, verification, location, status) values
('TT AUTOSPA KSL JB (BIKE CAR DETAILING)', 'CAR WASH', 'local entrepreneur Haziq (often referred to as Boss Haziq)', 'GOOGLE SEARCHES', '308, Jalan Dato Sulaiman, Taman Abad, 80250 Johor Bahru, Johor Darul Ta''zim', 'BUMI'),
('TT AUTO SPA HQ (Bike Car Detailing)', 'CAR WASH', 'local entrepreneur Haziq (often referred to as Boss Haziq)', 'GOOGLE SEARCHES', '57, Jln Meranti Merah, Taman Melodies, 80250 Johor Bahru, Johor Darul Ta''zim', 'BUMI'),
('JB Holiday Car Wash- Polish & Waxing + Coating', 'CAR WASH', 'THOMAS SNG', 'GOOGLE SEARCHES', '45, Jalan Kelewang 1, Taman Sri Tebrau, 80050 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('Supwave Automobile Car Care Centre', 'CAR WASH', 'EDDY SUPWAVE', 'GOOGLE SEARCHES', '221, Jalan Dato Sulaiman, Century Garden, 80250 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('TT Autospa Larkin JB', 'CAR WASH', 'local entrepreneur Haziq (often referred to as Boss Haziq)', 'GOOGLE SEARCHES', 'Jalan Kebun Teh 1, Larkin, 80250 Johor Bahru, Johor Darul Ta''zim', 'BUMI'),
('JUST SHINE SIGNATURE AUTO SPA SDN BHD', 'CAR WASH', 'Joscelin (branch manager)', 'GOOGLE SEARCHES', '107, Jalan Dato Sulaiman, Taman Abad, 80250 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('D''LUX - Premium Car Grooming Studio', 'CAR WASH', 'Steven', 'GOOGLE SEARCHES', '77, Jalan Serampang, Taman Sri Tebrau, 80050 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('JB Singapore Holiday Car Wash', 'CAR WASH', 'JUN', 'GOOGLE SEARCHES', '268, 270, Jalan Dato Sulaiman, Taman Century, 80250 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('R&R Auto Detailer Centre @ Tebrau - Premium Car Wash | Polishing | Coating | Detailing', 'CAR WASH', 'Farry Wong Hoong Chun and Simon Heong', 'GOOGLE SEARCHES', 'Lot 4112 Jalan Dato Abdullah Tahir, Jalan Tebrau, Taman Abad, 80300 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('Red Cube Auto Spa', 'CAR WASH', 'representative Ahmad Abu, alongside co-representative Nurshuhadah Hj Mohamad Hanis', 'GOOGLE SEARCHES', '28, Jalan Padi Emas 4/1, Bandar Baru Uda, 81200 Johor Bahru, Johor Darul Ta''zim', 'BUMI'),
('Bossgo Car Wash', 'CAR WASH', 'Ah Jian and Nick', 'GOOGLE SEARCHES', '167, Jalan Sutera, Taman Sentosa, 80150 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('RN SUPER CARWASH (JALAN HARIMAU)', 'CAR WASH', 'Raymond', 'GOOGLE SEARCHES', '47, Jalan Harimau, Taman Abad, 80250 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('Boss Clean Car Wash and Bike Spa', 'CAR WASH', 'Boss Fik', 'GOOGLE SEARCHES', 'Majidee, 35, Jalan Sempadan, Kampung Melayu Majidee, 81750 Johor Bahru, Johor Darul Ta''zim', 'BUMI'),
('786 Car Wash', 'CAR WASH', 'Raju Day Raju', 'GOOGLE SEARCHES', 'Jalan Bukit Chagar, Kim Teng Park, 80300 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('M8 Car Auto Detailing', 'CAR WASH', 'Hong: Manages the M8 Car Desa Tebrau hub', 'GOOGLE SEARCHES', '113, Jalan Perisai, Taman Sri Tebrau, 80050 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('Formula One Car Wash Sdn Bhd', 'CAR WASH', 'NO INFO', 'GOOGLE SEARCHES', '36, Jalan Sutera 4, Taman Sentosa, 80150 Johor Bahru, Johor Darul Ta''zim', '-'),
('A&A Carwash spa and detailing', 'CAR WASH', 'Hyrul Brother 7', 'GOOGLE SEARCHES', '36, Jalan Lembah 1, Taman Desa Jaya, 81100 Johor Bahru, Johor Darul Ta''zim', 'BUMI'),
('WASH ZONE LARKIN', 'CAR WASH', 'Mr. Nannu', 'GOOGLE SEARCHES', '2, Jln Dataran Larkin 2, Larkin Jaya, 80350 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('AX AutoExpress Car Wash & Detailing', 'CAR WASH', 'Shah Izan, Muhammad Azlan Shah, and operational point-of-contact Leo', 'GOOGLE SEARCHES', 'GF-05 Block 4, Batu 4 1/2, Lbh Skudai, Danga Bay, 80200 Johor Bahru, Johor Darul Ta''zim', 'BUMI'),
('RETRO Car Wash (Taman Bukit Mewah)', 'CAR WASH', 'Mohd Zubair Islam', 'GOOGLE SEARCHES', '11, Jalan Mewah Ria 5/4, Taman Bukit Mewah, 81200 Johor Bahru, Johor Darul Ta''zim', 'BUMI'),
('Extreme Car Wash', 'CAR WASH', 'Mr. Tanesh', 'GOOGLE SEARCHES', '165, Jalan Keris 1, Taman Sri Tebrau, 80050 Johor Bahru, Johor Darul Ta''zim', 'NON BUMI'),
('Legend Car Wash (Shell Taman Iskandar)', 'CAR WASH', null, 'GOOGLE SEARCHES', 'Jalan Pasir Pelangi, Taman Iskandar, 80050 Johor Bahru, Johor Darul Ta''zim', '-');
